version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16  # Image Docker utilisée par CircleCI
    steps:
      - checkout                # Cloner le dépôt
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Docker image
          command: docker build -t node-js-sample .

  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Run Docker container
          command: docker run -d -p 3000:3000 node-js-sample
      - run:
          name: Test application
          command: curl -f http://localhost:3000

  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Push Docker image to DockerHub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker tag node-js-sample $DOCKERHUB_USERNAME/node-js-sample
            docker push $DOCKERHUB_USERNAME/node-js-sample

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
